name: wiz-sca-scan

on:
  pull_request:
    branches: [ "main" ]

jobs:

  sca-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Wiz CLI
        run: |
          curl -o wizcli https://wizcli.app.wiz.io/wizcli
          chmod +x wizcli

      - name: Authenticate to Wiz
        run: |
          ./wizcli auth \
            --id "${{ secrets.WIZ_CLIENT_ID }}" \
            --secret "${{ secrets.WIZ_CLIENT_SECRET }}"


      - name: Run Wiz SCA / SBOM scan
        run: |
              ./wizcli dir scan --path .
